### ISSUE TITLE
resMulti function returns error with parameter order

### ISSUE THREAD

**Issue by chengmatt** [fishfollower/compResidual#4]
I had previously successfully implemented OSA residuals for a multinomial using the resmulti function. However, upon revisiting the code, it returns the following error:

Error in .Call("getParameterOrder", data, parameters, reportenv, control,  : 
  Incorrect number of arguments (4), expecting 3 for 'getParameterOrder'

I tried using the function via the example provided in the landing page and reinstalling, but it still returns the same error message. Looking at the source code, I couldn't quite figure out which parameters were missing since there is only 1 dummy variable. I am not sure if this is something on my end, and was wondering if someone would be able to help debug.

Thanks!

Matt

**Comment by vtrijoulet** [comment]
Hi Matt,

If you have updated TMB since you've used the compResidual package, you need to be sure the package is recompiled with the newer TMB version.
Try running:

```
TMB:::install.contrib("https://github.com/vtrijoulet/OSA_multivariate_dists/archive/main.zip")
devtools::install_github("fishfollower/compResidual/compResidual", force=TRUE) # to force the reinstallation of the package
```

And let us know if you still have the issue.
Cheers,
Vanessa

**Comment by chengmatt** [comment]
Hi Vanessa,

Thanks for the help here! I'm a new TMB user, so still figuring it out there. Your suggestion worked perfectly!

Cheers,

Matt
